// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { IngredientsApiPrivateCreateIngredientData, IngredientsApiPrivateCreateIngredientResponses, IngredientsApiPrivateGetAllergiesData, IngredientsApiPrivateGetAllergiesResponses, IngredientsApiPrivateGetIngredientDetailData, IngredientsApiPrivateGetIngredientDetailResponses, IngredientsApiPrivateGetIngredientsData, IngredientsApiPrivateGetIngredientsResponses, IngredientsApiPrivateUpdateIngredientData, IngredientsApiPrivateUpdateIngredientResponses, RecipesApiPrivateCreateRecipeData, RecipesApiPrivateCreateRecipeResponses, RecipesApiPrivateDeleteRecipeData, RecipesApiPrivateDeleteRecipeResponses, RecipesApiPrivateGetRecipeDetailData, RecipesApiPrivateGetRecipeDetailResponses, RecipesApiPrivateListRecipesData, RecipesApiPrivateListRecipesResponses, RecipesApiPrivateUpdateRecipeData, RecipesApiPrivateUpdateRecipeResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * List Recipes
 */
export const recipesApiPrivateListRecipes = <ThrowOnError extends boolean = false>(options?: Options<RecipesApiPrivateListRecipesData, ThrowOnError>) => (options?.client ?? client).get<RecipesApiPrivateListRecipesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/recipes/recipes/',
    ...options
});

/**
 * Create Recipe
 */
export const recipesApiPrivateCreateRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateCreateRecipeData, ThrowOnError>) => (options.client ?? client).post<RecipesApiPrivateCreateRecipeResponses, unknown, ThrowOnError>({
    querySerializer: { parameters: { recipe_data: { object: { style: 'form' } } } },
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/recipes/recipes/',
    ...options
});

/**
 * Delete Recipe
 */
export const recipesApiPrivateDeleteRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateDeleteRecipeData, ThrowOnError>) => (options.client ?? client).delete<RecipesApiPrivateDeleteRecipeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/recipes/recipes/{sqid}/',
    ...options
});

/**
 * Get Recipe Detail
 */
export const recipesApiPrivateGetRecipeDetail = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateGetRecipeDetailData, ThrowOnError>) => (options.client ?? client).get<RecipesApiPrivateGetRecipeDetailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/recipes/recipes/{sqid}/',
    ...options
});

/**
 * Update Recipe
 */
export const recipesApiPrivateUpdateRecipe = <ThrowOnError extends boolean = false>(options: Options<RecipesApiPrivateUpdateRecipeData, ThrowOnError>) => (options.client ?? client).put<RecipesApiPrivateUpdateRecipeResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/recipes/recipes/{sqid}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Ingredients
 */
export const ingredientsApiPrivateGetIngredients = <ThrowOnError extends boolean = false>(options?: Options<IngredientsApiPrivateGetIngredientsData, ThrowOnError>) => (options?.client ?? client).get<IngredientsApiPrivateGetIngredientsResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/ingredients/ingredients/',
    ...options
});

/**
 * Create Ingredient
 */
export const ingredientsApiPrivateCreateIngredient = <ThrowOnError extends boolean = false>(options: Options<IngredientsApiPrivateCreateIngredientData, ThrowOnError>) => (options.client ?? client).post<IngredientsApiPrivateCreateIngredientResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/ingredients/ingredients/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Ingredient Detail
 */
export const ingredientsApiPrivateGetIngredientDetail = <ThrowOnError extends boolean = false>(options: Options<IngredientsApiPrivateGetIngredientDetailData, ThrowOnError>) => (options.client ?? client).get<IngredientsApiPrivateGetIngredientDetailResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/ingredients/ingredients/{sqid}/',
    ...options
});

/**
 * Update Ingredient
 */
export const ingredientsApiPrivateUpdateIngredient = <ThrowOnError extends boolean = false>(options: Options<IngredientsApiPrivateUpdateIngredientData, ThrowOnError>) => (options.client ?? client).put<IngredientsApiPrivateUpdateIngredientResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/ingredients/ingredients/{sqid}/',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Allergies
 */
export const ingredientsApiPrivateGetAllergies = <ThrowOnError extends boolean = false>(options?: Options<IngredientsApiPrivateGetAllergiesData, ThrowOnError>) => (options?.client ?? client).get<IngredientsApiPrivateGetAllergiesResponses, unknown, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/private/ingredients/allergies/',
    ...options
});
