// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type MutationOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { ingredientsApiPrivateCreateIngredient, ingredientsApiPrivateGetAllergies, ingredientsApiPrivateGetIngredientDetail, ingredientsApiPrivateGetIngredients, ingredientsApiPrivateUpdateIngredient, type Options, recipesApiPrivateCreateRecipe, recipesApiPrivateDeleteRecipe, recipesApiPrivateGetRecipeDetail, recipesApiPrivateListRecipes, recipesApiPrivateUpdateRecipe } from '../sdk.gen';
import type { IngredientsApiPrivateCreateIngredientData, IngredientsApiPrivateCreateIngredientResponse, IngredientsApiPrivateGetAllergiesData, IngredientsApiPrivateGetAllergiesResponse, IngredientsApiPrivateGetIngredientDetailData, IngredientsApiPrivateGetIngredientDetailResponse, IngredientsApiPrivateGetIngredientsData, IngredientsApiPrivateGetIngredientsResponse, IngredientsApiPrivateUpdateIngredientData, IngredientsApiPrivateUpdateIngredientResponse, RecipesApiPrivateCreateRecipeData, RecipesApiPrivateDeleteRecipeData, RecipesApiPrivateGetRecipeDetailData, RecipesApiPrivateGetRecipeDetailResponse, RecipesApiPrivateListRecipesData, RecipesApiPrivateListRecipesResponse, RecipesApiPrivateUpdateRecipeData, RecipesApiPrivateUpdateRecipeResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const recipesApiPrivateListRecipesQueryKey = (options?: Options<RecipesApiPrivateListRecipesData>) => createQueryKey('recipesApiPrivateListRecipes', options);

/**
 * List Recipes
 */
export const recipesApiPrivateListRecipesOptions = (options?: Options<RecipesApiPrivateListRecipesData>) => queryOptions<RecipesApiPrivateListRecipesResponse, DefaultError, RecipesApiPrivateListRecipesResponse, ReturnType<typeof recipesApiPrivateListRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateListRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateListRecipesQueryKey(options)
});

/**
 * Create Recipe
 */
export const recipesApiPrivateCreateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateCreateRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreateRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateCreateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateCreateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete Recipe
 */
export const recipesApiPrivateDeleteRecipeMutation = (options?: Partial<Options<RecipesApiPrivateDeleteRecipeData>>): MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeleteRecipeData>> => {
    const mutationOptions: MutationOptions<unknown, DefaultError, Options<RecipesApiPrivateDeleteRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateDeleteRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recipesApiPrivateGetRecipeDetailQueryKey = (options: Options<RecipesApiPrivateGetRecipeDetailData>) => createQueryKey('recipesApiPrivateGetRecipeDetail', options);

/**
 * Get Recipe Detail
 */
export const recipesApiPrivateGetRecipeDetailOptions = (options: Options<RecipesApiPrivateGetRecipeDetailData>) => queryOptions<RecipesApiPrivateGetRecipeDetailResponse, DefaultError, RecipesApiPrivateGetRecipeDetailResponse, ReturnType<typeof recipesApiPrivateGetRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPrivateGetRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPrivateGetRecipeDetailQueryKey(options)
});

/**
 * Update Recipe
 */
export const recipesApiPrivateUpdateRecipeMutation = (options?: Partial<Options<RecipesApiPrivateUpdateRecipeData>>): MutationOptions<RecipesApiPrivateUpdateRecipeResponse, DefaultError, Options<RecipesApiPrivateUpdateRecipeData>> => {
    const mutationOptions: MutationOptions<RecipesApiPrivateUpdateRecipeResponse, DefaultError, Options<RecipesApiPrivateUpdateRecipeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await recipesApiPrivateUpdateRecipe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetIngredientsQueryKey = (options?: Options<IngredientsApiPrivateGetIngredientsData>) => createQueryKey('ingredientsApiPrivateGetIngredients', options);

/**
 * Get Ingredients
 */
export const ingredientsApiPrivateGetIngredientsOptions = (options?: Options<IngredientsApiPrivateGetIngredientsData>) => queryOptions<IngredientsApiPrivateGetIngredientsResponse, DefaultError, IngredientsApiPrivateGetIngredientsResponse, ReturnType<typeof ingredientsApiPrivateGetIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetIngredientsQueryKey(options)
});

/**
 * Create Ingredient
 */
export const ingredientsApiPrivateCreateIngredientMutation = (options?: Partial<Options<IngredientsApiPrivateCreateIngredientData>>): MutationOptions<IngredientsApiPrivateCreateIngredientResponse, DefaultError, Options<IngredientsApiPrivateCreateIngredientData>> => {
    const mutationOptions: MutationOptions<IngredientsApiPrivateCreateIngredientResponse, DefaultError, Options<IngredientsApiPrivateCreateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingredientsApiPrivateCreateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetIngredientDetailQueryKey = (options: Options<IngredientsApiPrivateGetIngredientDetailData>) => createQueryKey('ingredientsApiPrivateGetIngredientDetail', options);

/**
 * Get Ingredient Detail
 */
export const ingredientsApiPrivateGetIngredientDetailOptions = (options: Options<IngredientsApiPrivateGetIngredientDetailData>) => queryOptions<IngredientsApiPrivateGetIngredientDetailResponse, DefaultError, IngredientsApiPrivateGetIngredientDetailResponse, ReturnType<typeof ingredientsApiPrivateGetIngredientDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetIngredientDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetIngredientDetailQueryKey(options)
});

/**
 * Update Ingredient
 */
export const ingredientsApiPrivateUpdateIngredientMutation = (options?: Partial<Options<IngredientsApiPrivateUpdateIngredientData>>): MutationOptions<IngredientsApiPrivateUpdateIngredientResponse, DefaultError, Options<IngredientsApiPrivateUpdateIngredientData>> => {
    const mutationOptions: MutationOptions<IngredientsApiPrivateUpdateIngredientResponse, DefaultError, Options<IngredientsApiPrivateUpdateIngredientData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await ingredientsApiPrivateUpdateIngredient({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const ingredientsApiPrivateGetAllergiesQueryKey = (options?: Options<IngredientsApiPrivateGetAllergiesData>) => createQueryKey('ingredientsApiPrivateGetAllergies', options);

/**
 * Get Allergies
 */
export const ingredientsApiPrivateGetAllergiesOptions = (options?: Options<IngredientsApiPrivateGetAllergiesData>) => queryOptions<IngredientsApiPrivateGetAllergiesResponse, DefaultError, IngredientsApiPrivateGetAllergiesResponse, ReturnType<typeof ingredientsApiPrivateGetAllergiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPrivateGetAllergies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPrivateGetAllergiesQueryKey(options)
});
