// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions } from '@tanstack/svelte-query';

import { client } from '../client.gen';
import { camplistsApiGetKamplijst, camplistsApiListKamplijsts, ingredientsApiPublicGetAllergies, ingredientsApiPublicGetIngredientDetail, ingredientsApiPublicGetIngredients, type Options, recipesApiPublicGetCategories, recipesApiPublicGetRecipeDetail, recipesApiPublicGetRecipes, recipesApiPublicSearchRecipes } from '../sdk.gen';
import type { CamplistsApiGetKamplijstData, CamplistsApiListKamplijstsData, IngredientsApiPublicGetAllergiesData, IngredientsApiPublicGetAllergiesResponse, IngredientsApiPublicGetIngredientDetailData, IngredientsApiPublicGetIngredientDetailResponse, IngredientsApiPublicGetIngredientsData, IngredientsApiPublicGetIngredientsResponse, RecipesApiPublicGetCategoriesData, RecipesApiPublicGetCategoriesResponse, RecipesApiPublicGetRecipeDetailData, RecipesApiPublicGetRecipeDetailResponse, RecipesApiPublicGetRecipesData, RecipesApiPublicGetRecipesResponse, RecipesApiPublicSearchRecipesData, RecipesApiPublicSearchRecipesResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const ingredientsApiPublicGetIngredientsQueryKey = (options?: Options<IngredientsApiPublicGetIngredientsData>) => createQueryKey('ingredientsApiPublicGetIngredients', options);

/**
 * Get Ingredients
 */
export const ingredientsApiPublicGetIngredientsOptions = (options?: Options<IngredientsApiPublicGetIngredientsData>) => queryOptions<IngredientsApiPublicGetIngredientsResponse, DefaultError, IngredientsApiPublicGetIngredientsResponse, ReturnType<typeof ingredientsApiPublicGetIngredientsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetIngredients({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetIngredientsQueryKey(options)
});

export const ingredientsApiPublicGetIngredientDetailQueryKey = (options: Options<IngredientsApiPublicGetIngredientDetailData>) => createQueryKey('ingredientsApiPublicGetIngredientDetail', options);

/**
 * Get Ingredient Detail
 */
export const ingredientsApiPublicGetIngredientDetailOptions = (options: Options<IngredientsApiPublicGetIngredientDetailData>) => queryOptions<IngredientsApiPublicGetIngredientDetailResponse, DefaultError, IngredientsApiPublicGetIngredientDetailResponse, ReturnType<typeof ingredientsApiPublicGetIngredientDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetIngredientDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetIngredientDetailQueryKey(options)
});

export const ingredientsApiPublicGetAllergiesQueryKey = (options?: Options<IngredientsApiPublicGetAllergiesData>) => createQueryKey('ingredientsApiPublicGetAllergies', options);

/**
 * Get Allergies
 */
export const ingredientsApiPublicGetAllergiesOptions = (options?: Options<IngredientsApiPublicGetAllergiesData>) => queryOptions<IngredientsApiPublicGetAllergiesResponse, DefaultError, IngredientsApiPublicGetAllergiesResponse, ReturnType<typeof ingredientsApiPublicGetAllergiesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await ingredientsApiPublicGetAllergies({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: ingredientsApiPublicGetAllergiesQueryKey(options)
});

export const recipesApiPublicGetRecipesQueryKey = (options?: Options<RecipesApiPublicGetRecipesData>) => createQueryKey('recipesApiPublicGetRecipes', options);

/**
 * Get Recipes
 */
export const recipesApiPublicGetRecipesOptions = (options?: Options<RecipesApiPublicGetRecipesData>) => queryOptions<RecipesApiPublicGetRecipesResponse, DefaultError, RecipesApiPublicGetRecipesResponse, ReturnType<typeof recipesApiPublicGetRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetRecipesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const recipesApiPublicGetRecipesInfiniteQueryKey = (options?: Options<RecipesApiPublicGetRecipesData>): QueryKey<Options<RecipesApiPublicGetRecipesData>> => createQueryKey('recipesApiPublicGetRecipes', options, true);

/**
 * Get Recipes
 */
export const recipesApiPublicGetRecipesInfiniteOptions = (options?: Options<RecipesApiPublicGetRecipesData>) => infiniteQueryOptions<RecipesApiPublicGetRecipesResponse, DefaultError, InfiniteData<RecipesApiPublicGetRecipesResponse>, QueryKey<Options<RecipesApiPublicGetRecipesData>>, number | Pick<QueryKey<Options<RecipesApiPublicGetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<RecipesApiPublicGetRecipesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                offset: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await recipesApiPublicGetRecipes({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetRecipesInfiniteQueryKey(options)
});

export const recipesApiPublicSearchRecipesQueryKey = (options: Options<RecipesApiPublicSearchRecipesData>) => createQueryKey('recipesApiPublicSearchRecipes', options);

/**
 * Search Recipes
 */
export const recipesApiPublicSearchRecipesOptions = (options: Options<RecipesApiPublicSearchRecipesData>) => queryOptions<RecipesApiPublicSearchRecipesResponse, DefaultError, RecipesApiPublicSearchRecipesResponse, ReturnType<typeof recipesApiPublicSearchRecipesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicSearchRecipes({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicSearchRecipesQueryKey(options)
});

export const recipesApiPublicGetRecipeDetailQueryKey = (options: Options<RecipesApiPublicGetRecipeDetailData>) => createQueryKey('recipesApiPublicGetRecipeDetail', options);

/**
 * Get Recipe Detail
 */
export const recipesApiPublicGetRecipeDetailOptions = (options: Options<RecipesApiPublicGetRecipeDetailData>) => queryOptions<RecipesApiPublicGetRecipeDetailResponse, DefaultError, RecipesApiPublicGetRecipeDetailResponse, ReturnType<typeof recipesApiPublicGetRecipeDetailQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetRecipeDetail({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetRecipeDetailQueryKey(options)
});

export const recipesApiPublicGetCategoriesQueryKey = (options?: Options<RecipesApiPublicGetCategoriesData>) => createQueryKey('recipesApiPublicGetCategories', options);

/**
 * Get Categories
 */
export const recipesApiPublicGetCategoriesOptions = (options?: Options<RecipesApiPublicGetCategoriesData>) => queryOptions<RecipesApiPublicGetCategoriesResponse, DefaultError, RecipesApiPublicGetCategoriesResponse, ReturnType<typeof recipesApiPublicGetCategoriesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await recipesApiPublicGetCategories({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: recipesApiPublicGetCategoriesQueryKey(options)
});

export const camplistsApiListKamplijstsQueryKey = (options?: Options<CamplistsApiListKamplijstsData>) => createQueryKey('camplistsApiListKamplijsts', options);

/**
 * List Kamplijsts
 */
export const camplistsApiListKamplijstsOptions = (options?: Options<CamplistsApiListKamplijstsData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof camplistsApiListKamplijstsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await camplistsApiListKamplijsts({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: camplistsApiListKamplijstsQueryKey(options)
});

export const camplistsApiGetKamplijstQueryKey = (options: Options<CamplistsApiGetKamplijstData>) => createQueryKey('camplistsApiGetKamplijst', options);

/**
 * Get Kamplijst
 */
export const camplistsApiGetKamplijstOptions = (options: Options<CamplistsApiGetKamplijstData>) => queryOptions<unknown, DefaultError, unknown, ReturnType<typeof camplistsApiGetKamplijstQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await camplistsApiGetKamplijst({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: camplistsApiGetKamplijstQueryKey(options)
});
